- gz_topic_name: "/realsense/image"
  ros_topic_name: "/camera/image_raw"
  gz_type_name: "gz.msgs.Image"
  ros_type_name: "sensor_msgs/msg/Image"
  direction: GZ_TO_ROS

- gz_topic_name: "/realsense/camera_info"
  ros_topic_name: "/camera/camera_info"
  gz_type_name: "gz.msgs.CameraInfo"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  direction: GZ_TO_ROS

- gz_topic_name: "/realsense/depth_image"
  ros_topic_name: "/camera/depth/image_raw"
  gz_type_name: "gz.msgs.Image"
  ros_type_name: "sensor_msgs/msg/Image"
  direction: GZ_TO_ROS